### ISSUE TITLE
Add AR6/CMIP6 specific info

### ISSUE THREAD

**Issue by durack1** [matthew-mizielinski/matthew-mizielinski.github.io#1]
There are a number of AR6 "resources" that may be useful to link, an example is the:
[AR6_WG1_priority_variables_Public_v1.0](https://docs.google.com/spreadsheets/d/1H2qXofwjOpCospDcj9LRokpz0HGysRcDK2HmNSJoqyk/edit#gid=0)
[CMIP6 aerosols & land](https://docs.google.com/spreadsheets/d/1y91pk_18aFcKVt5kFelNZHHupCaeyJFh3r5QKWL8EPI/edit#gid=0)

And some other resources that were generated as input into the CMIP6 data request:
[CMIP6_OMIP_physics_standard_output](https://docs.google.com/spreadsheets/d/1M7KeHm1ZaSKClgf5O0L1-LZgWJJqaVlVTQ44jnZiT4A/edit#gid=87704053)
[CMIP6_OMIP_chemistry_standard_output](https://docs.google.com/spreadsheets/d/1SfxHKASSwLbPM6xBDjZ6Y8oIxx9APLOlCG9G0lzIu7o/edit#gid=999996017)
[CMIP6_OMIP_biogeochemistry_standard_output](https://docs.google.com/spreadsheets/d/1HFYLi9mEypLdos7IG07Rv5XqBLyQ9r_thiKaulIjfbw/edit#gid=1916409171) - likely deprecated

**Comment by matthew-mizielinski** [comment]
Hi @durack1,  I've thrown what I have into the pull request on the WIP pages along with the first four of the links from the above. If you're happy with that I'll close this down (and retire my pages so as not to spread confusion).

**Comment by matthew-mizielinski** [comment]
I think I've dealt with this in part. Some of this will need to be moved into a data request page, but re-open if I've missed something important

**Comment by durack1** [comment]
@matthew-mizielinski the new page looks great, thanks for pushing (and fixing the undisclosed issue with the file locations)
